// Copyright (c) Grzegorz Sołtysik
// Nazwa projektu: AESManager
// Nazwa pliku: AESManager.h
// Data: 26.12.2025, 07:26

//
// Created by GrzegorzS on 21.10.2025.
//

#ifndef AESMANAGER_AESMANAGER_H
#define AESMANAGER_AESMANAGER_H

#include <windows.h>
// Identyfikatory pozycji napisów tablicy GLOBAL_STRINGS
enum
{
	STR_INF0_TITLE=0, STR_TRAYMENU_EXIT, STR_TRAYHINT, STR_INFO_TEXT,
	// Opisy przycisków
	STR_BUTTON_TEXT, //4
	// Tekst opisów w statusbarze
	STR_LONG_OPEN_FILE, STR_LONG_RUN_PROCESS, STR_LONG_SAVECONFIG,
	STR_LONG_OPEN_DIR, STR_LONG_SAVE_HISTORY, STR_LONG_CLEARHISTORY,
	STR_LONG_INFO,
	// Teksty w podpowiedziach przycisków
	STR_TITLE_BUTTON_HINT, // Tytuł opisu
	// Tekst podpowiedzi
	STR_TEXT_HINT_OPEN_FILE, STR_TEXT_HINT_RUN_PROCESS, STR_TEXT_HINT_SAVECONFIG,
	STR_TEXT_HINT_OPEN_DIR, STR_TEXT_HINT_SAVE_HISTORY, STR_TEXT_HINT_CLEARHISTORY,
	STR_TEXT_HINT_INFO,
	// Identyfikacje w menu traya
	IDI_TRAY_EXIT = 1000,
	// Identyfikatory ikon w ImageList
	IDIMAGE_OPEN_FILE=0, IDIMAGE_RUN_PROCESS, IDIMAGE_SAVE_CONFIG,
	IDIMAGE_OPEN_DIR, IDIMAGE_SAVE_HISTORY, IDIMAGE_CLEARHISTORY,
	IDIMAGE_INFO,
	// Identyfikator numerów przycisków
	IDBUTTON_OPEN_FILE=1000, IDBUTTON_RUN_PROCESS, IDBUTTON_SAVECOFIG,
	IDBUTTON_OPEN_DIR, IDBUTTON_SAVE_HISTORY, IDBUTTON_CLEARHISTORY,
	IDBUTTON_INFO,

	IDBUTTON_VIEWPASS=100, IDEDIT_PASS, IDEDIT_PATH_INPUT, IDEDIT_PATH_OUTPUT,
	IDBUTTON_PATH_DIR
};

extern const TCHAR GLOBAL_CLASS_NAME[],
	GLOBAL_TITLE_WINDOW[],
	GLOBAL_FONT_NAME[],
	GLOBAL_CRYPT_EXT[],
	// Zmienne dla pliku .ini
	GLOBAL_CONFIGFILENAME[],
	GLOBAL_MAINSECTION[],
	GLOBAL_KEY_PASSWORD[],
	GLOBAL_TEXT_DEFAULT_PASSWORD[],
	GLOBAL_KEY_TYPEAES[], // Czy AES-128, czy AES-256.
	GLOBAL_AESTYPE[],					// Wersja uproszczona, czy profesjonalna.
	// Możliwe typy szyfrowania(długości klucza)
	GLOBAL_VALUE_SIZEAES_128[],
	GLOBAL_VALUE_SIZEAES_256[],
	// Możliwe typ szyfrowania AES
	GLOBAL_VALUE_TYPEAES_BASIC[],
	GLOBAL_VALUE_TYPEAES_PROFF[],
	// Nazwa pliku zapisanej histori operacji
	GLOBAL_HISTORY_FILE[];

extern const int ID_START_COUNT,
				GLOBAL_SIZE_FONT,
				GLOBAL_CODEPASS;
// Tablica napisów
extern const TCHAR *GLOBAL_STRINGS[];

#endif //AESMANAGER_AESMANAGER_H